### ISSUE TITLE
Infinite auto on simulation?

### ISSUE THREAD

**Issue by KalmAndKollected** [KIvoy/nikke-assistant#10] opened 2023-12-31 22:54 UTC
Is it possible for it to run simulation without stopping?
mine always stops after 1 game of simulation.

**Comment by KIvoy** [comment] 2024-01-01 07:30
Thanks for raising this issue, it's caused by a recent update of the game. A new version will be released soon with the fixes to this specific problem.

**Comment by KIvoy** [comment] 2024-01-01 09:32
The update has been released on [v1.4.4](https://github.com/KIvoy/nikke-assistant/releases/tag/v1.4.4), please let me know if the issue persists.

**Comment by KalmAndKollected** [comment] 2024-01-01 11:01
Serious bug on simulation. It starts selecting the sector and difficulty and it looks at this 

![this](https://github.com/KIvoy/nikke-assistant/assets/154399432/516626e2-8bb0-46ca-a6dd-abd922516ad5)
and then it thinks that the simulation is cleared already and goes back home.

`2024-01-01 18:55:40,951 - INFO - succesfully detected app window

2024-01-01 18:55:42,032 - INFO - Simulation room started...

2024-01-01 18:56:04,336 - INFO - Could not start simulation

2024-01-01 18:56:44,044 - INFO - Simulation room started...

2024-01-01 18:56:56,704 - INFO - starting simulation run difficulty 4 sector c...

2024-01-01 18:57:06,342 - INFO - Sector cleared, ignoring clear is set to false, exiting...

2024-01-01 18:57:06,345 - INFO - Simulation room ended.

2024-01-01 18:57:06,348 - INFO - Exiting to home...

2024-01-01 18:57:24,010 - INFO - Exited to home succesfully

2024-01-01 18:57:44,347 - INFO - Simulation room started...

2024-01-01 18:57:57,002 - INFO - starting simulation run difficulty 4 sector c...

2024-01-01 18:58:06,621 - INFO - Sector cleared, ignoring clear is set to false, exiting...

2024-01-01 18:58:06,625 - INFO - Simulation room ended.

2024-01-01 18:58:06,629 - INFO - Exiting to home...

2024-01-01 18:58:24,306 - INFO - Exited to home succesfully
`

**Comment by KIvoy** [comment] 2024-01-01 17:46
Hmm from what I see on the image it seems like you've already cleared sector 4C and you are trying to redo 4C? Is that the intended behavior? If yes then you should check the option in the settings to "打过也重打" and it'll ignore whether that sector has been completed or not.

**Comment by KalmAndKollected** [comment] 2024-01-01 17:47
ahh I didn't know about that one. I'm going to test it right now.

**Comment by KalmAndKollected** [comment] 2024-01-01 18:19
hello, it works fine now but how do I prevent it from stopping after simulation end / clear? like it being on repeat?

**Comment by KIvoy** [comment] 2024-01-01 20:10
Unfortunately the app was not originally designed to have repeat. If you want to repeat for certain achievements (not sure if it's still possible now), you could simply assign a mouse macro to repeat it.

**Comment by KalmAndKollected** [comment] 2024-01-01 23:38
I see, how unfortunate. Thank you for the app and the update anyways!

**Closed** 2024-01-02 00:57 UTC
